# Generated by Django 5.1.1 on 2024-09-16 13:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место привычки')),
                ('time', models.TimeField(verbose_name='время привычки')),
                ('action', models.CharField(max_length=200, verbose_name='действие привычки')),
                ('sign_of_a_pleasant_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность привычки')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.DurationField(default=datetime.timedelta(seconds=20), verbose_name='время на выполнение')),
                ('sign_of_publicity', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
