# Generated by Django 5.1.1 on 2024-09-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность привычки, в днях'),
        ),
    ]
