# Generated by Django 5.1.1 on 2024-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='телеграм chat-id'),
        ),
    ]
