# Generated by Django 5.1.1 on 2024-09-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_tg_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='tg_chat_id',
        ),
    ]
